/**
 * ReactFlow 视觉类型 ↔ 工作流域类型 的双向映射（Phase 6 从 WorkflowEditor.tsx 迁出）。
 * NodeShell 需要用 rfTypeToWfType 反查当前节点的域类型（损伤等级/端口类型），而编辑器
 * 也依赖同一份映射 —— 集中在这里避免组件层 → 页面层的循环 import。
 * "msst" 是旧工程兼容别名（pre-catalog 分离节点），加载后由 rfTypeToWfType 归一到 msstSeparation。
 */
export const rfTypeToWfType = {
    audioInput: "input",
    audioOutput: "output",
    rvc: "rvc",
    sovits: "sovits",
    separation: "msstSeparation",
    transpose: "transpose",
    amtMidi: "amtMidi",
    speedShift: "speedShift",
    chordDetect: "chordDetect",
    autoArrange: "autoArrange",
    deepOriginal: "deepOriginal",
    midiFileIn: "midiFileIn",
    chordBlockIn: "chordBlockIn",
    soundfontRender: "soundfontRender",
    melodySimilarity: "melodySimilarity",
    split: "split",
    merge: "merge",
    complianceCheck: "complianceCheck",
    lufsNormalize: "lufsNormalize",
    dither: "dither",
    busEq: "busEq",
    stereoWidth: "stereoWidth",
    saturate: "saturate",
    phaseRotate: "phaseRotate",
    dcRemove: "dcRemove",
    // Phase 5 分析可视化节点族 (rf type === wf type)
    spectrogram: "spectrogram",
    f0Curve: "f0Curve",
    timbreMetrics: "timbreMetrics",
    harmonicityCheck: "harmonicityCheck",
    spectralCompare: "spectralCompare",
    dtwAlign: "dtwAlign",
    abCompare: "abCompare",
    lufsAnalyze: "lufsAnalyze",
    harmonizer: "harmonizer",
    melodyGen: "melodyGen",
    msst: "msstSeparation",
    songLyrics: "songLyrics",
    songPrompt: "songPrompt",
    songGen: "songGen",
    songCover: "songCover",
    songRepaint: "songRepaint",
    songComplete: "songComplete",
    songExtract: "songExtract",
    songLego: "songLego",
    songStems: "songStems",
    songSheet: "songSheet",
    songGenYue2: "songGenYue2",
    songGenAceStep: "songGenAceStep",
    // P2 符号域原创化节点族 (rf type === wf type)
    midiHumanize: "midiHumanize",
    velocityCurve: "velocityCurve",
    swingQuantize: "swingQuantize",
    melodyReharm: "melodyReharm",
    rhythmRestructure: "rhythmRestructure",
    contourMorph: "contourMorph",
    motifDevelop: "motifDevelop",
    reharmonize: "reharmonize",
    rhythmVariation: "rhythmVariation",
    structureEdit: "structureEdit",
    breathPlanner: "breathPlanner",
};
export const wfTypeToRfType = {
    input: "audioInput",
    output: "audioOutput",
    rvc: "rvc",
    sovits: "sovits",
    msstSeparation: "separation",
    transpose: "transpose",
    amtMidi: "amtMidi",
    speedShift: "speedShift",
    chordDetect: "chordDetect",
    autoArrange: "autoArrange",
    deepOriginal: "deepOriginal",
    midiFileIn: "midiFileIn",
    chordBlockIn: "chordBlockIn",
    soundfontRender: "soundfontRender",
    split: "split",
    merge: "merge",
    complianceCheck: "complianceCheck",
    lufsNormalize: "lufsNormalize",
    dither: "dither",
    busEq: "busEq",
    stereoWidth: "stereoWidth",
    saturate: "saturate",
    phaseRotate: "phaseRotate",
    dcRemove: "dcRemove",
    // Phase 5 分析可视化节点族 (wf type === rf type)
    spectrogram: "spectrogram",
    f0Curve: "f0Curve",
    timbreMetrics: "timbreMetrics",
    harmonicityCheck: "harmonicityCheck",
    spectralCompare: "spectralCompare",
    dtwAlign: "dtwAlign",
    abCompare: "abCompare",
    lufsAnalyze: "lufsAnalyze",
    harmonizer: "harmonizer",
    melodyGen: "melodyGen",
    songLyrics: "songLyrics",
    songPrompt: "songPrompt",
    songGen: "songGen",
    songCover: "songCover",
    songRepaint: "songRepaint",
    songComplete: "songComplete",
    songExtract: "songExtract",
    songLego: "songLego",
    songStems: "songStems",
    songSheet: "songSheet",
    songGenYue2: "songGenYue2",
    songGenAceStep: "songGenAceStep",
    melodySimilarity: "melodySimilarity",
    midiHumanize: "midiHumanize",
    velocityCurve: "velocityCurve",
    swingQuantize: "swingQuantize",
    melodyReharm: "melodyReharm",
    rhythmRestructure: "rhythmRestructure",
    contourMorph: "contourMorph",
    motifDevelop: "motifDevelop",
    reharmonize: "reharmonize",
    rhythmVariation: "rhythmVariation",
    structureEdit: "structureEdit",
    breathPlanner: "breathPlanner",
};
