fn main() {
    embed_utai_train();
    tauri_build::build()
}

/// S168: embed the bundled trainer package (`training/utai_train`, ~1.2 MB of pure `.py`)
/// into the binary, so `training::bundled_code::sync_bundled_training_code` can verify and
/// restore it at runtime. The incident that bought this: on installs whose data root is the
/// install root, earlier boots' migrations mangled the tree and a phantom "utai_train"
/// project row invited its deletion — after which training and the pack self-test failed
/// (`ENVTEST_SCRIPT_MISSING` / `No module named 'utai_train'`) with no repair short of a
/// reinstall. The installer keeps shipping the tree as loose resources (the sidecar imports
/// from disk); this embed is the repair source, not the runtime import path.
///
/// Filtered to `*.py` on purpose: the dev machine's checkout grows `__pycache__/` under this
/// tree (the sidecar runs with cwd=training), and embedding whatever bytecode happens to be
/// lying around would make builds irreproducible. The module's own tests pin the filter
/// (no `__pycache__`, everything `.py`, the load-bearing files present).
fn embed_utai_train() {
    use std::fmt::Write as _;
    let src = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("training")
        .join("utai_train");
    let mut files: Vec<(String, std::path::PathBuf)> = Vec::new();
    collect_py(&src, &src, &mut files);
    files.sort_by(|a, b| a.0.cmp(&b.0));
    // A moved/emptied tree must fail the BUILD, not silently ship a heal that restores
    // nothing (the tree holds 124 files today).
    assert!(
        files.len() >= 100,
        "utai_train embed collected only {} files under {} — did the tree move?",
        files.len(),
        src.display()
    );
    let mut out = String::new();
    out.push_str("/// (generated by build.rs) Every bundled trainer source file, as\n");
    out.push_str("/// (path relative to training/utai_train with forward slashes, file bytes).\n");
    out.push_str("pub static UTAI_TRAIN_FILES: &[(&str, &[u8])] = &[\n");
    for (rel, abs) in &files {
        let abs_s = abs.to_string_lossy().replace('\\', "/");
        writeln!(out, "    ({rel:?}, include_bytes!({abs_s:?})),").unwrap();
        println!("cargo:rerun-if-changed={abs_s}");
    }
    out.push_str("];\n");
    let dst = std::path::Path::new(&std::env::var("OUT_DIR").unwrap()).join("utai_train_embed.rs");
    std::fs::write(&dst, out).expect("write utai_train embed");
    // ⚠ Deliberately NO directory-level rerun-if-changed (reviewed S168): cargo tracks a
    // directory RECURSIVELY by mtime, and the dev sidecar writes __pycache__ under this
    // tree (cwd = training), so a dir line would dirty the whole crate after every dev
    // training run. Cost accepted instead: ADDING a brand-new .py without touching any
    // existing one needs a `cargo clean -p utai` (or any edit to a tracked file) before the
    // embed sees it — the embed test's load-bearing-file pins catch a stale shipped set.
}

fn collect_py(root: &std::path::Path, dir: &std::path::Path, out: &mut Vec<(String, std::path::PathBuf)>) {
    let Ok(rd) = std::fs::read_dir(dir) else { return };
    for e in rd.flatten() {
        let p = e.path();
        let name = e.file_name().to_string_lossy().into_owned();
        if p.is_dir() {
            if name == "__pycache__" {
                continue;
            }
            collect_py(root, &p, out);
        } else if name.ends_with(".py") {
            let rel = p
                .strip_prefix(root)
                .expect("child under root")
                .to_string_lossy()
                .replace('\\', "/");
            out.push((rel, p));
        }
    }
}
