//! Shared DSP + ContentVec extraction for the voice-conversion pipelines (RVC + SoVITS).
//!
//! Every routine here is a faithful port of the ORIGINAL inference code:
//! - RVC: D:\MyDev\RVC\RVC20240604Nvidia\infer\modules\vc\pipeline.py
//! - so-vits-svc 4.1-Stable: inference\infer_tool.py + utils.py
//!
//! Reference vectors in the unit tests were generated by running the ORIGINAL python
//! (ast-extracted so the exact original lines execute) in the converter venv
//! (scipy 1.15.3 / numpy 2.2.6 / torch 2.12.0 / librosa 0.11.0). Generator:
//! scratchpad gen_refs.py — the per-test comments carry the exact recipe.

use ndarray::{Array2, Axis};
use rayon::prelude::*;

use super::engine::{InputTensor, OnnxEngine};
use crate::{Result, UtaiError};

/// ContentVec input sample rate (both variants).
pub const CONTENTVEC_SR: u32 = 16000;
/// Minimum ContentVec input length (conv front-end receptive field).
pub const CONTENTVEC_MIN_SAMPLES: usize = 400;

// ─── ContentVec (vec768l12 / vec256l9) ──────────────────────────────────────

/// Run a ContentVec extractor: raw mono 16 kHz f32 (NO normalization) → features [T, dim],
/// T = (N-400)/320 + 1 (50 fps). Contract: converter\verify\voice\gate_contentvec.py.
pub fn contentvec_extract(
    engine: &OnnxEngine,
    session_id: &str,
    wav16k: &[f32],
    dim: usize,
) -> Result<Array2<f32>> {
    let n = wav16k.len();
    if n < CONTENTVEC_MIN_SAMPLES {
        return Err(UtaiError::Inference(format!(
            "音频片段过短，无法提取内容特征（{} 采样点 < {}）",
            n, CONTENTVEC_MIN_SAMPLES
        )));
    }
    let t = (n - CONTENTVEC_MIN_SAMPLES) / 320 + 1;
    let input = InputTensor::F32 {
        data: wav16k.to_vec(),
        shape: vec![1, n as i64],
    };
    let outputs = engine.run(session_id, vec![("waveform", input)])?;
    let feats = outputs
        .into_iter()
        .next()
        .ok_or_else(|| UtaiError::Inference("ContentVec 模型没有返回输出".into()))?;
    if feats.len() != t * dim {
        return Err(UtaiError::Inference(format!(
            "ContentVec 输出尺寸异常：期望 {}x{}={}，得到 {}",
            t,
            dim,
            t * dim,
            feats.len()
        )));
    }
    Array2::from_shape_vec((t, dim), feats)
        .map_err(|e| UtaiError::Inference(format!("ContentVec 输出重排失败: {}", e)))
}

// ─── Resampling (scipy-exact resample_poly from utai-dsp) ────────────────────

/// Rational resampler — scipy.signal.resample_poly semantics (utai-dsp, S34-verified vs scipy).
/// NOTE deviation from the originals' resamplers (RVC: ffmpeg swr at load; so-vits: torchaudio
/// sinc Resample): per task decision the whole pipeline standardizes on resample_poly.
pub fn resample(x: &[f32], from_sr: u32, to_sr: u32) -> Vec<f32> {
    if from_sr == to_sr {
        return x.to_vec();
    }
    utai_dsp::vr::resample_poly_f32(x, to_sr as usize, from_sr as usize)
}

// ─── np.pad(..., mode="reflect") — multi-bounce triangle indexing ────────────

/// numpy/torch 'reflect' padding (edge sample NOT repeated), supporting pad > len-1 via
/// the same repeated-bounce numpy applies. Verified against np.pad incl. multi-bounce
/// (converter venv: np.pad([1,2,3],(5,5),'reflect') etc.).
pub fn reflect_pad_np(x: &[f32], pad_left: usize, pad_right: usize) -> Vec<f32> {
    let n = x.len();
    assert!(n > 0, "reflect_pad_np on empty input");
    let total = pad_left + n + pad_right;
    if n == 1 {
        return vec![x[0]; total];
    }
    let period = (2 * (n - 1)) as i64;
    let mut out = Vec::with_capacity(total);
    for i in 0..total {
        let pos = i as i64 - pad_left as i64;
        let m = pos.rem_euclid(period);
        let idx = if (m as usize) < n { m as usize } else { (period - m) as usize };
        out.push(x[idx]);
    }
    out
}

// ─── scipy.signal.filtfilt(butter(5, 48, 'high', fs=16000)) ─────────────────

// Provenance: converter\.venv (scipy 1.15.3):
//   python -c "from scipy import signal; import numpy as np;
//              b,a = signal.butter(5,48,btype='high',fs=16000);
//              zi = signal.lfilter_zi(b,a); print(repr(b),repr(a),repr(zi))"
// (exact values below printed at 17 significant digits by scratchpad gen_refs.py)
const BUTTER_HP48_B: [f64; 6] = [
    9.69960645183844727e-01,
    -4.84980322591922342e+00,
    9.69960645183844683e+00,
    -9.69960645183844683e+00,
    4.84980322591922342e+00,
    -9.69960645183844727e-01,
];
const BUTTER_HP48_A: [f64; 6] = [
    1.00000000000000000e+00,
    -4.93900181916836356e+00,
    9.75786352673954305e+00,
    -9.63954484941345768e+00,
    4.76150679735620930e+00,
    -9.40823653205460575e-01,
];
/// scipy.signal.lfilter_zi(b, a) — steady-state initial conditions, hardcoded so Rust
/// needs no linear solver.
const BUTTER_HP48_ZI: [f64; 5] = [
    -9.69960479699584655e-01,
    3.87984192889257828e+00,
    -5.81976290817304331e+00,
    3.87984194847245600e+00,
    -9.69960489492338707e-01,
];

/// scipy filtfilt default edge extension: padtype='odd', padlen=None → edge = 3*max(len(a),len(b))
/// (= 18 here; verified against scipy 1.15.3 _validate_pad source — NOT 3*(ntaps-1)).
const FILTFILT_EDGE: usize = 18;

/// Direct-form II transposed lfilter with initial conditions (scipy.signal.lfilter zi semantics).
/// Assumes a[0] == 1 (scipy butter output is normalized).
fn lfilter_df2t(b: &[f64], a: &[f64], x: &[f64], zi: &[f64]) -> Vec<f64> {
    let order = b.len() - 1;
    let mut z = zi.to_vec();
    debug_assert_eq!(z.len(), order);
    let mut y = Vec::with_capacity(x.len());
    for &xi in x {
        let yi = b[0] * xi + z[0];
        for k in 0..order - 1 {
            z[k] = b[k + 1] * xi + z[k + 1] - a[k + 1] * yi;
        }
        z[order - 1] = b[order] * xi - a[order] * yi;
        y.push(yi);
    }
    y
}

/// scipy.signal.filtfilt(b, a, x) with the default pad method (odd extension, edge=3*ntaps,
/// zi-scaled forward + backward passes). f64 throughout, like scipy (the original pipeline's
/// audio is float64 after filtfilt; we cast back to f32 for the rest of the chain — fp32
/// noise floor, documented deviation).
fn filtfilt(b: &[f64], a: &[f64], zi: &[f64], x: &[f64]) -> Result<Vec<f64>> {
    let n = x.len();
    let edge = FILTFILT_EDGE;
    if n <= edge {
        return Err(UtaiError::Audio(format!(
            "音频太短，无法进行高通滤波（{} 采样点 ≤ {}）",
            n, edge
        )));
    }
    // odd extension: 2*x[0] - x[edge..1], x, 2*x[-1] - x[n-2..n-1-edge]
    let mut ext = Vec::with_capacity(n + 2 * edge);
    for j in (1..=edge).rev() {
        ext.push(2.0 * x[0] - x[j]);
    }
    ext.extend_from_slice(x);
    for j in 1..=edge {
        ext.push(2.0 * x[n - 1] - x[n - 1 - j]);
    }
    // forward
    let zi_fwd: Vec<f64> = zi.iter().map(|&v| v * ext[0]).collect();
    let y = lfilter_df2t(b, a, &ext, &zi_fwd);
    // backward
    let mut y_rev: Vec<f64> = y.into_iter().rev().collect();
    let zi_bwd: Vec<f64> = zi.iter().map(|&v| v * y_rev[0]).collect();
    y_rev = lfilter_df2t(b, a, &y_rev, &zi_bwd);
    y_rev.reverse();
    Ok(y_rev[edge..edge + n].to_vec())
}

/// The RVC pipeline's 48 Hz high-pass at 16 kHz: signal.filtfilt(bh, ah, audio)
/// (pipeline.py line 318, bh/ah from butter(N=5, Wn=48, btype="high", fs=16000)).
pub fn highpass_48hz_16k(x: &[f32]) -> Result<Vec<f32>> {
    let x64: Vec<f64> = x.iter().map(|&v| v as f64).collect();
    let y = filtfilt(&BUTTER_HP48_B, &BUTTER_HP48_A, &BUTTER_HP48_ZI, &x64)?;
    Ok(y.into_iter().map(|v| v as f32).collect())
}

// ─── librosa.feature.rms + change_rms (RVC pipeline.py / so-vits utils.py) ──

/// librosa.feature.rms(y, frame_length, hop_length) with the librosa DEFAULTS the originals
/// rely on: center=True, pad_mode='constant' (ZERO padding — librosa's rms default differs
/// from stft's reflect; verified against librosa 0.11.0 signature + reference vector).
pub fn librosa_rms(y: &[f32], frame_length: usize, hop_length: usize) -> Vec<f32> {
    let pad = frame_length / 2;
    let padded_len = y.len() + 2 * pad;
    if padded_len < frame_length {
        return vec![];
    }
    let n_frames = (padded_len - frame_length) / hop_length + 1;
    let mut out = Vec::with_capacity(n_frames);
    for t in 0..n_frames {
        let start = t * hop_length;
        let mut acc = 0.0f64;
        for i in start..start + frame_length {
            // padded[i]: zeros outside [pad, pad+len)
            if i >= pad && i < pad + y.len() {
                let v = y[i - pad] as f64;
                acc += v * v;
            }
        }
        out.push((acc / frame_length as f64).sqrt() as f32);
    }
    out
}

/// torch F.interpolate(mode="linear", align_corners=False) 1-D — used by change_rms.
pub fn torch_interp_linear(src: &[f32], dst_len: usize) -> Vec<f32> {
    if src.is_empty() || dst_len == 0 {
        return vec![0.0; dst_len];
    }
    let src_len = src.len();
    let scale = src_len as f64 / dst_len as f64;
    (0..dst_len)
        .map(|i| {
            let x = ((i as f64 + 0.5) * scale - 0.5).max(0.0);
            let i0 = (x.floor() as usize).min(src_len - 1);
            let i1 = if i0 < src_len - 1 { i0 + 1 } else { i0 };
            let frac = (x - i0 as f64) as f32;
            src[i0] + (src[i1] - src[i0]) * frac
        })
        .collect()
}

/// torch F.interpolate(mode="nearest") 1-D: src index = floor(dst_index * src/dst).
pub fn torch_interp_nearest(src: &[f32], dst_len: usize) -> Vec<f32> {
    let src_len = src.len();
    let scale = src_len as f64 / dst_len as f64;
    (0..dst_len)
        .map(|i| src[((i as f64 * scale) as usize).min(src_len - 1)])
        .collect()
}

/// RVC pipeline.py change_rms (identical function in so-vits utils.py): rms every half
/// second on both signals, linear-interp both to the output sample count, then
/// out *= rms1^(1-rate) * rms2^(rate-1) with rms2 floored at 1e-6.
pub fn change_rms(data1: &[f32], sr1: u32, data2: &mut [f32], sr2: u32, rate: f32) {
    let rms1 = librosa_rms(data1, (sr1 / 2 * 2) as usize, (sr1 / 2) as usize);
    let rms2 = librosa_rms(data2, (sr2 / 2 * 2) as usize, (sr2 / 2) as usize);
    let rms1 = torch_interp_linear(&rms1, data2.len());
    let rms2 = torch_interp_linear(&rms2, data2.len());
    for (i, v) in data2.iter_mut().enumerate() {
        let r2 = rms2[i].max(1e-6);
        *v *= rms1[i].powf(1.0 - rate) * r2.powf(rate - 1.0);
    }
}

// ─── np.interp (for the so-vits f0 gap interpolation) ───────────────────────

/// np.interp(x, xp, fp) with left=fp[0], right=fp[last]. xp must be increasing.
pub fn np_interp(x: &[f64], xp: &[f64], fp: &[f64]) -> Vec<f64> {
    debug_assert_eq!(xp.len(), fp.len());
    debug_assert!(!xp.is_empty());
    x.iter()
        .map(|&xi| {
            if xi <= xp[0] {
                fp[0]
            } else if xi >= xp[xp.len() - 1] {
                fp[fp.len() - 1]
            } else {
                // last j with xp[j] <= xi
                let j = match xp.binary_search_by(|v| v.partial_cmp(&xi).unwrap()) {
                    Ok(j) => return fp[j],
                    Err(ins) => ins - 1,
                };
                let t = (xi - xp[j]) / (xp[j + 1] - xp[j]);
                fp[j] + t * (fp[j + 1] - fp[j])
            }
        })
        .collect()
}

// ─── repeat_expand_2d (so-vits utils.py, 'left' + 'nearest') ─────────────────

/// so-vits utils.repeat_expand_2d — content here is [T, dim] (frames as rows; the original
/// is [h, t]). 'left' ports repeat_expand_2d_left's loop bug-for-bug (boundary tensor is
/// float32 in torch: int64 arange * int → true-divide promotes to f32); anything else uses
/// F.interpolate 'nearest' semantics (the only other mode shipped configs use).
pub fn repeat_expand_2d(content: &Array2<f32>, target_len: usize, mode: &str) -> Result<Array2<f32>> {
    let src_len = content.nrows();
    let dim = content.ncols();
    if src_len == 0 {
        return Err(UtaiError::Inference("repeat_expand_2d：空特征".into()));
    }
    let mut out = Array2::<f32>::zeros((target_len, dim));
    if mode == "left" {
        // temp[k] = float32((k*target) as f32 / src as f32) — torch int64/int true-divide → f32
        let boundary = |k: usize| ((k as i64 * target_len as i64) as f32) / (src_len as f32);
        let mut current_pos = 0usize;
        for i in 0..target_len {
            if (i as f32) < boundary(current_pos + 1) {
                // stay
            } else {
                // .min() is protective only: the original indexes content[:, pos] unclamped
                // and never overruns in practice (boundary(src_len) == target_len exactly)
                current_pos = (current_pos + 1).min(src_len - 1);
            }
            out.row_mut(i).assign(&content.row(current_pos));
        }
    } else if mode == "nearest" {
        let scale = src_len as f64 / target_len as f64;
        for i in 0..target_len {
            let src_i = ((i as f64 * scale) as usize).min(src_len - 1);
            out.row_mut(i).assign(&content.row(src_i));
        }
    } else {
        return Err(UtaiError::Inference(format!(
            "不支持的 unit_interpolate_mode：{}（当前支持 left / nearest）",
            mode
        )));
    }
    Ok(out)
}

/// RVC vc(): F.interpolate(feats.permute(0,2,1), scale_factor=2) — nearest = repeat each
/// frame twice (50 fps → 100 fps).
pub fn upsample_2x_nearest(feats: &Array2<f32>) -> Array2<f32> {
    let (t, dim) = (feats.nrows(), feats.ncols());
    let mut out = Array2::<f32>::zeros((t * 2, dim));
    for i in 0..t {
        out.row_mut(2 * i).assign(&feats.row(i));
        out.row_mut(2 * i + 1).assign(&feats.row(i));
    }
    out
}

/// L2-normalize feature rows in place (optional post-retrieval step; NOT in the official
/// pipeline — exposed as the l2_normalize option).
// ─── KNN feature retrieval (RVC vc() faiss semantics, shared with so-vits) ──

const KNN_TOP_K: usize = 8;
/// Frames per gemm block (rayon-parallel across blocks; the [block,dim]@[dim,N] product
/// runs in matrixmultiply, which has a dev-profile opt override).
const KNN_BLOCK: usize = 64;

/// Retrieval index: raw vectors + precomputed squared row norms (|v|²), so per-query
/// distances are d² = |q|² − 2·q·v + |v|². Replaces the old cosine-normalized copy
/// (halves RAM; faiss IndexFlatL2 semantics are squared-L2, not cosine).
pub struct KnnIndex {
    pub vectors: Array2<f32>,
    norms: Vec<f32>,
}

impl KnnIndex {
    pub fn new(vectors: Array2<f32>) -> Self {
        let norms = vectors
            .rows()
            .into_iter()
            .map(|r| r.iter().map(|&v| v * v).sum::<f32>())
            .collect();
        Self { vectors, norms }
    }

    pub fn len(&self) -> usize {
        self.vectors.nrows()
    }

    pub fn dim(&self) -> usize {
        self.vectors.ncols()
    }
}

/// Original (pipeline.py vc / infer_tool.get_unit_f0 feature retrieval):
///   score, ix = index.search(npy, k=8)           # faiss squared-L2
///   weight = np.square(1 / score); weight /= weight.sum(axis=1, keepdims=True)
///   npy = sum(big_npy[ix] * weight[..., None], axis=1)
///   feats = ratio * npy + (1 - ratio) * feats
/// Ours is EXACT brute-force top-8 (faiss IVF nprobe=1 is approximate) and clamps the
/// squared distance at 1e-9 — the original's exact-match case is 1/0 = inf → NaN.
///
/// `cosine_metric` (RVC's L2归一化 option, OUR extra): neighbor selection + 1/d⁴ weights
/// use the unit-normalized distance d² = 2 − 2·cos(q,v) instead of raw squared-L2, but the
/// retrieved vectors are blended at their ORIGINAL scale. S36 fix: the first version
/// normalized the blended features THEMSELVES (the model input) — unit-norm ContentVec is
/// far outside the synthesizer's training distribution and audibly muffles the output.
pub fn knn_blend(
    features: &Array2<f32>,
    index: &KnnIndex,
    ratio: f32,
    cosine_metric: bool,
) -> Array2<f32> {
    let t = features.nrows();
    let dim = features.ncols();
    if index.len() == 0 || dim != index.dim() {
        tracing::warn!(
            "检索索引维度不匹配（特征 {}，索引 {}）——跳过检索",
            dim,
            index.dim()
        );
        return features.clone();
    }
    let k = KNN_TOP_K.min(index.len());

    let block_starts: Vec<usize> = (0..t).step_by(KNN_BLOCK).collect();
    let blocks: Vec<Array2<f32>> = block_starts
        .par_iter()
        .map(|&start| {
            let end = (start + KNN_BLOCK).min(t);
            let q = features.slice(ndarray::s![start..end, ..]);
            // sims[b][j] = q_b · v_j
            let sims = q.dot(&index.vectors.t());
            let mut out = Array2::<f32>::zeros((end - start, dim));
            let mut cand: Vec<(f32, usize)> = Vec::with_capacity(index.len());
            for (bi, q_row) in q.rows().into_iter().enumerate() {
                let qn: f32 = q_row.iter().map(|&v| v * v).sum();
                let q_norm = qn.sqrt().max(1e-12);
                cand.clear();
                for j in 0..index.len() {
                    let d2 = if cosine_metric {
                        // squared L2 of the unit-normalized pair: 2 − 2·cos(q, v)
                        let v_norm = index.norms[j].sqrt().max(1e-12);
                        2.0 - 2.0 * sims[[bi, j]] / (q_norm * v_norm)
                    } else {
                        qn - 2.0 * sims[[bi, j]] + index.norms[j]
                    };
                    cand.push((d2, j));
                }
                cand.select_nth_unstable_by(k - 1, |a, b| a.0.partial_cmp(&b.0).unwrap());
                // weights over the k nearest (f32, matching the original numpy dtype chain)
                let mut wsum = 0.0f32;
                let mut w = [0.0f32; KNN_TOP_K];
                for (wi, &(d2, _)) in cand[..k].iter().enumerate() {
                    let inv = 1.0 / d2.max(1e-9);
                    w[wi] = inv * inv;
                    wsum += w[wi];
                }
                let mut retrieved = vec![0.0f32; dim];
                for (wi, &(_, j)) in cand[..k].iter().enumerate() {
                    let wn = w[wi] / wsum;
                    let v = index.vectors.row(j);
                    for (r, &vv) in retrieved.iter_mut().zip(v.iter()) {
                        *r += vv * wn;
                    }
                }
                for (c, (&orig, &ret)) in q_row.iter().zip(retrieved.iter()).enumerate() {
                    out[[bi, c]] = ratio * ret + (1.0 - ratio) * orig;
                }
            }
            out
        })
        .collect();

    let views: Vec<_> = blocks.iter().map(|b| b.view()).collect();
    ndarray::concatenate(Axis(0), &views).expect("knn block concat")
}

/// so-vits cluster kmeans path (cluster/__init__.py get_cluster_center_result):
/// per frame, replace with the L2-nearest center; caller blends with cluster_ratio.
pub fn nearest_cluster_centers(features: &Array2<f32>, centers: &KnnIndex) -> Array2<f32> {
    let t = features.nrows();
    let dim = features.ncols();
    let mut out = Array2::<f32>::zeros((t, dim));
    if centers.len() == 0 || dim != centers.dim() {
        tracing::warn!(
            "聚类中心维度不匹配（特征 {}，中心 {}）——跳过聚类",
            dim,
            centers.dim()
        );
        return features.clone();
    }
    let block_starts: Vec<usize> = (0..t).step_by(KNN_BLOCK).collect();
    let rows: Vec<(usize, Vec<usize>)> = block_starts
        .par_iter()
        .map(|&start| {
            let end = (start + KNN_BLOCK).min(t);
            let q = features.slice(ndarray::s![start..end, ..]);
            let sims = q.dot(&centers.vectors.t());
            let mut picks = Vec::with_capacity(end - start);
            for (bi, q_row) in q.rows().into_iter().enumerate() {
                let qn: f32 = q_row.iter().map(|&v| v * v).sum();
                let mut best = (f32::INFINITY, 0usize);
                for j in 0..centers.len() {
                    let d2 = qn - 2.0 * sims[[bi, j]] + centers.norms[j];
                    if d2 < best.0 {
                        best = (d2, j);
                    }
                }
                picks.push(best.1);
            }
            (start, picks)
        })
        .collect();
    for (start, picks) in rows {
        for (off, j) in picks.into_iter().enumerate() {
            out.row_mut(start + off).assign(&centers.vectors.row(j));
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use ndarray::Array2;

    // All reference vectors below were generated by scratchpad gen_refs.py run with
    // D:\MyDev\Utai_v2-dev\converter\.venv\Scripts\python.exe against the ORIGINAL code
    // (RVC pipeline.py / so-vits utils.py, ast-extracted so the original lines execute).

    fn assert_close(got: &[f32], want: &[f32], tol: f32, label: &str) {
        assert_eq!(got.len(), want.len(), "{}: length {} vs {}", label, got.len(), want.len());
        for (i, (g, w)) in got.iter().zip(want.iter()).enumerate() {
            let scale = w.abs().max(1.0);
            assert!(
                (g - w).abs() <= tol * scale,
                "{}: idx {} got {} want {} (tol {})",
                label, i, g, w, tol
            );
        }
    }

    // python: from scipy import signal; b,a = signal.butter(5,48,btype='high',fs=16000)
    //         x1 = sin(2π·3·i/40)+0.3·sin(2π·0.5·i/40), i=0..39 (also a ramp and seeded randn)
    //         y = signal.filtfilt(b, a, x)  # defaults: padtype='odd', padlen=None → edge 18
    #[test]
    fn filtfilt_matches_scipy_reference() {
        const FILTFILT_IN_1: &[f64] = &[0.00000000000000000e+00, 4.77528228457900217e-01, 8.55947333887016715e-01, 1.05772194975190947e+00, 1.04376161460763783e+00, 8.21911810896074457e-01, 4.45214144296811498e-01, 3.15104374553898392e-04, -4.11449676604731085e-01, -6.96172109689312757e-01, -7.87867965644035717e-01, -6.62884734508358830e-01, -3.45080153979989146e-01, 9.93575842659965291e-02, 5.76318951631457521e-01, 9.84270640939933328e-01, 1.23637347118369956e+00, 1.27939931671444085e+00, 1.10532349655348883e+00, 7.53065699859486237e-01, 3.00000000000000377e-01, -1.54915299619608871e-01, -5.12710492196405854e-01, -6.95977364475834803e-01, -6.65739561406607727e-01, -4.29942921433162428e-01, -4.17150371184375479e-02, 4.12226514346457185e-01, 8.30490350604956906e-01, 1.11912831386837652e+00, 1.21213203435596428e+00, 1.08584093868742371e+00, 7.64120827980215522e-01, 3.13184034455015248e-01, -1.72819844453081073e-01, -5.92301751477020688e-01, -8.58351417982669229e-01, -9.17654731438366289e-01, -7.62086654862879631e-01, -4.30452771021193115e-01];
        const FILTFILT_OUT_1: &[f64] = &[3.08669573186753810e-01, 7.80001443395978988e-01, 1.15248234924002046e+00, 1.34858638910790951e+00, 1.32923271205683524e+00, 1.10227655757659559e+00, 7.20769435908225509e-01, 2.71367889658719330e-01, -1.44582246415863314e-01, -4.33162530459292316e-01, -5.28378228951232765e-01, -4.06566175299324928e-01, -9.15732972571514092e-02, 3.50423177722031631e-01, 8.25324840504734869e-01, 1.23160965958687463e+00, 1.48244988680550427e+00, 1.52462898749395515e+00, 1.35013403075636096e+00, 9.97896615899431794e-01, 5.45302887468026132e-01, 9.13233820378317462e-02, -2.65059797461168367e-01, -4.46425877727085307e-01, -4.13785778777553070e-01, -1.75072448278821291e-01, 2.16599578794747727e-01, 6.74525950614213055e-01, 1.09732867892191122e+00, 1.39107316972787354e+00, 1.48976478771291410e+00, 1.36975686558414478e+00, 1.05492928313523859e+00, 6.11508624814820267e-01, 1.33658914800583339e-01, -2.77016187420284332e-01, -5.33591634553103100e-01, -5.82738358002392598e-01, -4.16316186356974094e-01, -7.31153886229138905e-02];
        const FILTFILT_IN_2: &[f64] = &[-2.50000000000000000e-01, -2.26190476190476164e-01, -2.02380952380952384e-01, -1.78571428571428603e-01, -1.54761904761904767e-01, -1.30952380952380931e-01, -1.07142857142857151e-01, -8.33333333333333703e-02, -5.95238095238095344e-02, -3.57142857142856984e-02, -1.19047619047619180e-02, 1.19047619047618625e-02, 3.57142857142856984e-02, 5.95238095238095344e-02, 8.33333333333333148e-02, 1.07142857142857095e-01, 1.30952380952380931e-01, 1.54761904761904767e-01, 1.78571428571428548e-01, 2.02380952380952328e-01, 2.26190476190476164e-01, 2.50000000000000000e-01, 2.73809523809523725e-01, 2.97619047619047561e-01, 3.21428571428571397e-01, 3.45238095238095233e-01, 3.69047619047619069e-01, 3.92857142857142794e-01, 4.16666666666666630e-01, 4.40476190476190466e-01, 4.64285714285714191e-01, 4.88095238095238027e-01, 5.11904761904761862e-01, 5.35714285714285698e-01, 5.59523809523809534e-01, 5.83333333333333259e-01, 6.07142857142857095e-01, 6.30952380952380931e-01, 6.54761904761904656e-01, 6.78571428571428492e-01, 7.02380952380952328e-01, 7.26190476190476164e-01, 7.50000000000000000e-01, 7.73809523809523725e-01, 7.97619047619047450e-01, 8.21428571428571397e-01, 8.45238095238095122e-01, 8.69047619047619069e-01, 8.92857142857142794e-01, 9.16666666666666519e-01, 9.40476190476190466e-01, 9.64285714285714191e-01, 9.88095238095238138e-01, 1.01190476190476186e+00, 1.03571428571428559e+00, 1.05952380952380953e+00, 1.08333333333333326e+00, 1.10714285714285698e+00, 1.13095238095238093e+00, 1.15476190476190466e+00, 1.17857142857142838e+00, 1.20238095238095233e+00, 1.22619047619047605e+00, 1.25000000000000000e+00];
        const FILTFILT_OUT_2: &[f64] = &[-1.11941704031947753e-01, -1.03468400390622328e-01, -9.51974530763191884e-02, -8.71289097908120869e-02, -7.92627757877294725e-02, -7.15990133019513419e-02, -6.41375409786591744e-02, -5.68782333020595721e-02, -4.98209200237989813e-02, -4.29653855910872573e-02, -3.63113685745470038e-02, -2.98585610958053138e-02, -2.36066082548429257e-02, -1.75551075571157011e-02, -1.17036083404628288e-02, -6.05161120181496592e-03, -5.98567423715556934e-04, 4.65612159933231906e-03, 9.71310493468235947e-03, 1.45730826855141327e-02, 1.92368065649438647e-02, 2.37050804702666762e-02, 2.79787610573217216e-02, 3.20587583149706534e-02, 3.59460361396804207e-02, 3.96416129102043768e-02, 4.31465620623533164e-02, 4.64620126638478348e-02, 4.95891499892491261e-02, 5.25292160949572262e-02, 5.52835103942746486e-02, 5.78533902325290977e-02, 6.02402714622489177e-02, 6.24456290183884322e-02, 6.44709974935976649e-02, 6.63179717135328195e-02, 6.79882073122038688e-02, 6.94834213073534379e-02, 7.08053926758674124e-02, 7.19559629292120390e-02, 7.29370366888955901e-02, 7.37505822619517332e-02, 7.43986322164419955e-02, 7.48832839569759656e-02, 7.52067003002468981e-02, 7.53711100505808779e-02, 7.53788085754972942e-02, 7.52321583812821659e-02, 7.49335896885659908e-02, 7.44856010079150838e-02, 7.38907597154262186e-02, 7.31517026283289573e-02, 7.22711365805941697e-02, 7.12518389985444534e-02, 7.00966584764708411e-02, 6.88085153522519366e-02, 6.73904022829754507e-02, 6.58453848205639153e-02, 6.41766019873998145e-02, 6.23872668519527274e-02, 6.04806671044086919e-02, 5.84601656322991658e-02, 5.63292010961302658e-02, 5.40912885050156000e-02];
        const FILTFILT_IN_3: &[f64] = &[1.49014245903369785e-01, -4.14792903513553982e-02, 1.94306561430207747e-01, 4.56908956922407572e-01, -7.02460124170007916e-02, -7.02410870847541557e-02, 4.73763844652217436e-01, 2.30230418745872634e-01, -1.40842315780485616e-01, 1.62768013075789392e-01, -1.39025307843738677e-01, -1.39718926071077054e-01, 7.25886814698102345e-02, -5.73984073397339367e-01, -5.17475349753909852e-01, -1.68686258772291792e-01, -3.03849336100327105e-01, 9.42741997785821600e-02, -2.72407222656363246e-01, -4.23691110400587434e-01, 4.39694630676466192e-01, -6.77328901459606919e-02, 2.02584614063771491e-02, -4.27424455864037045e-01, -1.63314817357554792e-01, 3.32767769129598268e-02, -3.45298073226690816e-01, 1.12709405503701579e-01, -1.80191606975641488e-01, -8.75081249379830312e-02, -1.80511983668819070e-01, 5.55683455352681266e-01, -4.04916742138017576e-03, -3.17313278686770117e-01, 2.46763473630956687e-01, -3.66253094991306649e-01, 6.26590785014266155e-02, -5.87901037163932605e-01, -3.98455814669529118e-01, 5.90583707607370556e-02, 2.21539973998623130e-01, 5.14104843569911443e-02, -3.46944847164721570e-02, -9.03311086767866339e-02, -4.43556597110228212e-01, -2.15953262518412598e-01, -1.38191631287936240e-01, 3.17136667865674682e-01, 1.03085486870538423e-01, -5.28912046608820186e-01, 9.72251908184385005e-02, -1.15524684124894958e-01, -2.03076600091787601e-01, 1.83502886652260361e-01, 3.09299856748785296e-01, 2.79384035734859537e-01, -2.51765256966791529e-01, -9.27637127553643664e-02, 9.93790294210691871e-02, 2.92663538136707757e-01, -1.43752271353586980e-01, -5.56976929991451347e-02, -3.31900492201808450e-01, -3.58861987224201207e-01, 2.43757746718259394e-01, 4.06872008571246890e-01, -2.16030364741001540e-02, 3.01059869367607258e-01, 1.08490807514290244e-01, -1.93535926381537271e-01, 1.08418681652524176e-01, 4.61410969939790749e-01, -1.07478117329854617e-02, 4.69393096744201821e-01, -7.85923531226923267e-01, 2.46570751312567144e-01, 2.61141204714513651e-02, -8.97022051397602382e-02, 2.75282329606506872e-02, -5.96270674380267818e-01, -6.59015663512535765e-02, 1.07133771453523916e-01, 4.43368213422454804e-01, -1.55481065482094200e-01, -2.42548080867956262e-01, -1.50527113075360958e-01, 2.74620635310622252e-01, 9.86253328979053295e-02, -1.58928061130111625e-01, 1.53980229934006813e-01, 2.91232648044121162e-02, 2.90593497159866765e-01, -2.10615928163205707e-01, -9.82986439793304551e-02, -1.17632445939647279e-01, -4.39054484439635573e-01, 8.88360831193728134e-02, 7.83165816539667936e-02, 1.53403699273826693e-03, -7.03761400125440667e-02];
        const FILTFILT_OUT_3: &[f64] = &[-9.07751800346579540e-02, -2.77522529914239313e-01, -3.79921938047378255e-02, 2.28352696975218789e-01, -2.95062043093921700e-01, -2.91319421128354628e-01, 2.56420418687518525e-01, 1.66188674362130299e-02, -3.50725259332490102e-01, -4.33898113438453900e-02, -3.41461711387118061e-01, -3.38437804174918644e-01, -1.22416751006779817e-01, -7.65280311273084157e-01, -7.05066801749918093e-01, -3.52577477425475350e-01, -4.84045003523561279e-01, -8.22307135013461143e-02, -4.45226278887474736e-01, -5.92829291354245003e-01, 2.74232274249330388e-01, -2.29524525712204303e-01, -1.37867593445672343e-01, -5.81890089826118340e-01, -3.14125192756861515e-01, -1.13883487207082745e-01, -4.88813340387529660e-01, -2.71659277606709493e-02, -3.16431999480030646e-01, -2.20118480847715625e-01, -3.09497098756314204e-01, 4.30318913507354295e-01, -1.25797655234317796e-01, -4.35450062749598577e-01, 1.32234232900676263e-01, -4.77178741623941804e-01, -4.46666903864759712e-02, -6.91630389696650694e-01, -4.98591934809217430e-01, -3.74874006734071119e-02, 1.28581991088284164e-01, -3.79619230901227511e-02, -1.20483158639526633e-01, -1.72537495507953526e-01, -5.22181723003323772e-01, -2.90997708191321314e-01, -2.09655506478406223e-01, 2.49253750331249524e-01, 3.87844373957197952e-02, -5.89629767684183959e-01, 4.00928355130575342e-02, -1.69069031776321405e-01, -2.53029665820417748e-01, 1.37145037760502242e-01, 2.66541848902768219e-01, 2.40231211477242690e-01, -2.87306807330896530e-01, -1.24687121339850632e-01, 7.10814382919282561e-02, 2.68000278527149138e-01, -1.64771816001483828e-01, -7.30632384855225414e-02, -3.45600821798336677e-01, -3.68884919512487863e-01, 2.37425390399290226e-01, 4.04244437069126272e-01, -2.05105507903525497e-02, 3.05888781854129932e-01, 1.17073647786245183e-01, -1.81180491466329086e-01, 1.24566578845017872e-01, 4.81372433112569831e-01, 1.30495928765781422e-02, 4.97050126076919341e-01, -7.54381849586544528e-01, 2.82023494003466879e-01, 6.55057513662998525e-02, -4.63424028327174761e-02, 7.48869839792791203e-02, -5.44880664831076333e-01, -1.04464171123534871e-02, 1.66689552094202442e-01, 5.07061767334856195e-01, -8.76109062729822641e-02, -1.70460753792697872e-01, -7.41802842384100131e-02, 3.55271112304854697e-01, 1.83625458511267825e-01, -6.95303904109996207e-02, 2.47825280621076588e-01, 1.27467511440369663e-01, 3.93490779979818073e-01, -1.03109701142194768e-01, 1.38745469618822767e-02, -7.32115344557582315e-04, -3.17364637737661770e-01, 2.15380068197714214e-01, 2.09781618684129895e-01, 1.37989376737991221e-01, 7.11411366730773514e-02];

        for (name, x, want) in [
            ("sine", FILTFILT_IN_1, FILTFILT_OUT_1),
            ("ramp", FILTFILT_IN_2, FILTFILT_OUT_2),
            ("randn", FILTFILT_IN_3, FILTFILT_OUT_3),
        ] {
            let y = filtfilt(&BUTTER_HP48_B, &BUTTER_HP48_A, &BUTTER_HP48_ZI, x).unwrap();
            assert_eq!(y.len(), want.len());
            for (i, (g, w)) in y.iter().zip(want.iter()).enumerate() {
                assert!(
                    (g - w).abs() < 1e-9,
                    "filtfilt {} idx {}: got {} want {}",
                    name, i, g, w
                );
            }
        }
        // too-short input must error like scipy (padlen check)
        assert!(filtfilt(&BUTTER_HP48_B, &BUTTER_HP48_A, &BUTTER_HP48_ZI, &vec![0.0; 18]).is_err());
    }

    // python: rng=np.random.RandomState(7); index=rng.randn(10,4).f32;
    //         queries=[index[3] (EXACT match → d²=0 → 1e-9 eps path), randn, randn];
    //         d² sorted top-8, weight=(1/max(d²,1e-9))², normalized, blend ratio 0.75 / 1.0
    #[test]
    fn knn_blend_matches_numpy_reference() {
        const KNN_INDEX: &[f32] = &[1.690525651e+00, -4.659373760e-01, 3.282016516e-02, 4.075162709e-01, -7.889230251e-01, 2.065572888e-03, -8.903858834e-04, -1.754724264e+00, 1.017657995e+00, 6.004984975e-01, -6.254289746e-01, -1.715482622e-01, 5.052993894e-01, -2.613564134e-01, -2.427490801e-01, -1.453241467e+00, 5.545803308e-01, 1.238809079e-01, 2.744599283e-01, -1.526524544e+00, 1.650699735e+00, 1.543355286e-01, -3.871399462e-01, 2.029072285e+00, -4.538603127e-02, -1.450678706e+00, -4.052278697e-01, -2.288315058e+00, 1.049396515e+00, -4.164743125e-01, -7.425535321e-01, 1.072470188e+00, -1.651075602e+00, 5.354293585e-01, -2.064414740e+00, -6.621593237e-01, -1.204219818e+00, 1.461975574e+00, 1.766160846e+00, -3.294137418e-01];
        const KNN_QUERIES: &[f32] = &[5.052993894e-01, -2.613564134e-01, -2.427490801e-01, -1.453241467e+00, 8.407332301e-01, -1.799864024e-01, 5.680618882e-01, -7.528371811e-01, -1.708339214e+00, -1.803098679e+00, 3.831218481e-01, 2.247595072e+00];
        const KNN_BLEND_075: &[f32] = &[5.052993894e-01, -2.613564134e-01, -2.427490801e-01, -1.453241467e+00, 6.667164564e-01, -4.780784622e-02, 1.730403751e-01, -1.125167727e+00, -3.002169915e-02, -3.858610690e-01, -1.605358571e-01, 7.434017062e-01];
        const KNN_BLEND_100: &[f32] = &[5.052993894e-01, -2.613564134e-01, -2.427490801e-01, -1.453241467e+00, 6.087108850e-01, -3.748327494e-03, 4.136653244e-02, -1.249277949e+00, 5.294174552e-01, 8.655148000e-02, -3.417550921e-01, 2.420038879e-01];

        let index = KnnIndex::new(Array2::from_shape_vec((10, 4), KNN_INDEX.to_vec()).unwrap());
        let queries = Array2::from_shape_vec((3, 4), KNN_QUERIES.to_vec()).unwrap();
        let b075 = knn_blend(&queries, &index, 0.75, false);
        let b100 = knn_blend(&queries, &index, 1.0, false);
        assert_close(b075.as_slice().unwrap(), KNN_BLEND_075, 1e-4, "knn 0.75");
        assert_close(b100.as_slice().unwrap(), KNN_BLEND_100, 1e-4, "knn 1.0");
        // exact-match row must come back as the index vector itself (eps clamp, no NaN)
        assert!(b100.iter().all(|v| v.is_finite()), "NaN in knn output");
    }

    // cosine-metric mode (RVC L2归一化, S36 semantics): neighbor CHOICE ignores vector
    // magnitude, but the blended output stays at the ORIGINAL index-vector scale.
    #[test]
    fn knn_blend_cosine_metric_selects_by_angle_keeps_scale() {
        // index: v0 = big vector along +x, v1 = tiny vector along +y
        let index = KnnIndex::new(
            Array2::from_shape_vec((2, 2), vec![10.0, 0.0, 0.0, 0.01]).unwrap(),
        );
        // query along +y: L2-nearest is v1 for both metrics, but for a query along +x
        // with small magnitude, squared-L2 prefers TINY v1 (closer in space) while
        // cosine prefers v0 (same direction).
        let q = Array2::from_shape_vec((1, 2), vec![0.02, 0.0]).unwrap();
        let l2 = knn_blend(&q, &index, 1.0, false);
        let cosine = knn_blend(&q, &index, 1.0, true);
        // k = min(8, 2) = 2 → both neighbors contribute, but weights (1/d²)² concentrate
        // on the nearest: L2 → v1 (y-axis), cosine → v0 (x-axis, ORIGINAL 10.0 scale).
        assert!(l2[[0, 1]].abs() > l2[[0, 0]].abs(), "L2 metric should favor tiny v1");
        assert!(
            cosine[[0, 0]] > 9.0,
            "cosine metric must pick same-direction v0 at ORIGINAL scale, got {:?}",
            cosine
        );
        assert!(cosine.iter().all(|v| v.is_finite()));
    }

    // python (original so-vits utils.repeat_expand_2d, ast-exec):
    //   content [2,5] → 12 ('left' and 'nearest'), content [2,7] → 13
    // (original layout is [h, t]; ours is [T, dim] — references transposed accordingly)
    #[test]
    fn repeat_expand_2d_matches_torch_reference() {
        const RE2D_CONTENT: &[f32] = &[1.0, 2.0, 3.0, 4.0, 5.0, 10.0, -1.5, 0.25, 7.0, -3.0];
        const RE2D_LEFT_5TO12: &[f32] = &[1.000000000e+00, 1.000000000e+00, 1.000000000e+00, 2.000000000e+00, 2.000000000e+00, 3.000000000e+00, 3.000000000e+00, 3.000000000e+00, 4.000000000e+00, 4.000000000e+00, 5.000000000e+00, 5.000000000e+00, 1.000000000e+01, 1.000000000e+01, 1.000000000e+01, -1.500000000e+00, -1.500000000e+00, 2.500000000e-01, 2.500000000e-01, 2.500000000e-01, 7.000000000e+00, 7.000000000e+00, -3.000000000e+00, -3.000000000e+00];
        const RE2D_NEAREST_5TO12: &[f32] = RE2D_LEFT_5TO12; // identical for this geometry (both from the original)
        const RE2D_CONTENT7: &[f32] = &[-1.0, -0.5, 0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5];
        const RE2D_LEFT_7TO13: &[f32] = &[-1.000000000e+00, -1.000000000e+00, -5.000000000e-01, -5.000000000e-01, 0.000000000e+00, 0.000000000e+00, 5.000000000e-01, 5.000000000e-01, 1.000000000e+00, 1.000000000e+00, 1.500000000e+00, 1.500000000e+00, 2.000000000e+00, 2.500000000e+00, 2.500000000e+00, 3.000000000e+00, 3.000000000e+00, 3.500000000e+00, 3.500000000e+00, 4.000000000e+00, 4.000000000e+00, 4.500000000e+00, 4.500000000e+00, 5.000000000e+00, 5.000000000e+00, 5.500000000e+00];

        // reference layout: [h=2, t] flattened; ours: [t, h] — transpose helper
        let to_frames = |flat: &[f32], t: usize| {
            let mut a = Array2::<f32>::zeros((t, 2));
            for h in 0..2 {
                for i in 0..t {
                    a[[i, h]] = flat[h * t + i];
                }
            }
            a
        };
        let content = to_frames(RE2D_CONTENT, 5);
        let left = repeat_expand_2d(&content, 12, "left").unwrap();
        let nearest = repeat_expand_2d(&content, 12, "nearest").unwrap();
        let want12 = to_frames(RE2D_LEFT_5TO12, 12);
        let want12n = to_frames(RE2D_NEAREST_5TO12, 12);
        assert_close(left.as_slice().unwrap(), want12.as_slice().unwrap(), 0.0, "left 5→12");
        assert_close(nearest.as_slice().unwrap(), want12n.as_slice().unwrap(), 0.0, "nearest 5→12");

        let content7 = to_frames(RE2D_CONTENT7, 7);
        let left7 = repeat_expand_2d(&content7, 13, "left").unwrap();
        let nearest7 = repeat_expand_2d(&content7, 13, "nearest").unwrap();
        let want13 = to_frames(RE2D_LEFT_7TO13, 13);
        assert_close(left7.as_slice().unwrap(), want13.as_slice().unwrap(), 0.0, "left 7→13");
        assert_close(nearest7.as_slice().unwrap(), want13.as_slice().unwrap(), 0.0, "nearest 7→13");
    }

    // python: F.interpolate(feats.permute(0,2,1), scale_factor=2).permute(0,2,1)
    //         on [[[1,2],[3,4],[5,6]]] → each frame repeated twice
    #[test]
    fn upsample_2x_matches_torch_reference() {
        const UPS2X_OUT: &[f32] = &[1.0, 2.0, 1.0, 2.0, 3.0, 4.0, 3.0, 4.0, 5.0, 6.0, 5.0, 6.0];
        let feats = Array2::from_shape_vec((3, 2), vec![1.0, 2.0, 3.0, 4.0, 5.0, 6.0]).unwrap();
        let up = upsample_2x_nearest(&feats);
        assert_close(up.as_slice().unwrap(), UPS2X_OUT, 0.0, "2x upsample");
    }

    // python: F.interpolate(torch.tensor([[[1.,3.,2.,5.]]]), size=11, mode='linear')
    #[test]
    fn torch_interp_linear_matches_torch_reference() {
        const LERP_OUT_11: &[f32] = &[1.000000000e+00, 1.090909123e+00, 1.818181753e+00, 2.545454502e+00, 2.863636255e+00, 2.500000000e+00, 2.136363506e+00, 2.681818247e+00, 3.772727728e+00, 4.863636494e+00, 5.000000000e+00];
        let got = torch_interp_linear(&[1.0, 3.0, 2.0, 5.0], 11);
        assert_close(&got, LERP_OUT_11, 1e-6, "linear interp");
    }

    // python: librosa.feature.rms(y=sin(i*0.7)*0.6 (20 samples), frame_length=8, hop_length=4)
    //         → librosa DEFAULTS: center=True, pad_mode='constant' (zeros)
    #[test]
    fn librosa_rms_matches_reference() {
        const RMS_IN: &[f32] = &[0.000000000e+00, 3.865306079e-01, 5.912698507e-01, 5.179256201e-01, 2.009928972e-01, -2.104699314e-01, -5.229454637e-01, -5.894715786e-01, -3.787599802e-01, 1.008834038e-02, 3.941919506e-01, 5.929009318e-01, 5.127593279e-01, 1.914590150e-01, -2.198874801e-01, -5.278174281e-01, -5.875066519e-01, -3.708822727e-01, 2.017382905e-02, 4.017418623e-01];
        const RMS_OUT: &[f32] = &[3.096879125e-01, 4.290829301e-01, 4.117226303e-01, 3.995310068e-01, 3.985978067e-01, 2.838400304e-01];
        let got = librosa_rms(RMS_IN, 8, 4);
        assert_close(&got, RMS_OUT, 1e-6, "librosa rms");
    }

    // python (original RVC pipeline.py change_rms, ast-exec):
    //   rng=np.random.RandomState(5); d1=randn(40)*0.5, d2=randn(37)*0.2 (both f32)
    //   change_rms(d1, 16, d2, 16, rate) for rate 0.25 and 0.9
    #[test]
    fn change_rms_matches_original_reference() {
        const CHANGERMS_IN1: &[f32] = &[2.206137478e-01, -1.654350758e-01, 1.215385556e+00, -1.260460615e-01, 5.480492115e-02, 7.912405729e-01, -4.546161890e-01, -2.958183289e-01, 9.380161017e-02, -1.649349779e-01, -5.963823199e-01, -1.024382561e-01, -1.794144809e-01, 3.017357886e-01, -8.323942423e-01, -3.500895202e-01, 5.756955147e-01, 9.286655188e-01, -7.555897832e-01, 3.224237561e-01, -4.903039336e-01, -4.284265637e-01, -4.359395802e-01, -2.112539709e-01, 4.982199073e-01, 3.562106490e-01, 2.957212180e-02, -1.816554368e-01, 1.644421485e-03, -5.296522006e-02, 3.965266645e-01, -3.157858253e-01, -3.097454319e-03, -5.053380504e-02, -2.615407482e-02, 1.246088296e-01, 9.883004427e-02, 6.674242616e-01, -4.343780130e-02, 7.807661295e-01];
        const CHANGERMS_IN2: &[f32] = &[-6.117060408e-02, -9.554628283e-02, 2.014763840e-02, 7.108769566e-02, 5.392248183e-02, 2.583926618e-01, 2.278686017e-01, 9.888807684e-02, -6.726725399e-02, -2.012286894e-02, 2.826796174e-01, 4.425082356e-02, -2.621546388e-01, -1.379130483e-01, -1.155026481e-01, 2.304409593e-01, -2.143279649e-02, 4.520213604e-01, 1.313238889e-01, 2.496136539e-02, -8.714078367e-02, 1.944358647e-01, -4.814222828e-02, -1.648246944e-01, 1.136265472e-01, 2.551663434e-03, 2.378121465e-01, -1.471866388e-02, -5.719376206e-01, 1.578732878e-01, -3.755481839e-01, 3.077512383e-01, 3.642729521e-01, -8.540627360e-02, -2.329403758e-01, -2.794148028e-01, 1.745309234e-01];
        const CHANGERMS_OUT_R025: &[f32] = &[-1.756118685e-01, -2.742994130e-01, 5.784092471e-02, 2.065610886e-01, 1.535647213e-01, 7.147406340e-01, 6.140385270e-01, 2.602546811e-01, -1.732787937e-01, -5.054143444e-02, 6.818864942e-01, 1.035878882e-01, -6.035081148e-01, -3.123471439e-01, -2.574494779e-01, 5.051974654e-01, -4.573637247e-02, 9.390565157e-01, 2.656360865e-01, 4.828960821e-02, -1.614241153e-01, 3.452658057e-01, -8.054640889e-02, -2.593193352e-01, 1.680122316e-01, 3.543167841e-03, 3.144152761e-01, -1.867630705e-02, -7.038818002e-01, 1.890418530e-01, -4.370901883e-01, 3.477640748e-01, 3.991867602e-01, -9.065011889e-02, -2.438976914e-01, -2.925582528e-01, 1.827407032e-01];
        const CHANGERMS_OUT_R090: &[f32] = &[-7.040620595e-02, -1.099719629e-01, 2.318955027e-02, 8.195239305e-02, 6.199729443e-02, 2.959347069e-01, 2.600674331e-01, 1.125065610e-01, -7.631254196e-02, -2.275189571e-02, 3.178948760e-01, 4.956476390e-02, -2.929820120e-01, -1.537952721e-01, -1.285302341e-01, 2.558663487e-01, -2.371209487e-02, 4.983066618e-01, 1.442567557e-01, 2.725710534e-02, -9.460651875e-02, 2.099068761e-01, -5.156189203e-02, -1.750910729e-01, 1.197093278e-01, 2.665830310e-03, 2.468330711e-01, -1.519350801e-02, -5.879884362e-01, 1.617118567e-01, -3.832243383e-01, 3.128079772e-01, 3.687455654e-01, -8.608753234e-02, -2.343724072e-01, -2.811325490e-01, 1.756038666e-01];

        let mut d2 = CHANGERMS_IN2.to_vec();
        change_rms(CHANGERMS_IN1, 16, &mut d2, 16, 0.25);
        assert_close(&d2, CHANGERMS_OUT_R025, 1e-4, "change_rms 0.25");

        let mut d2b = CHANGERMS_IN2.to_vec();
        change_rms(CHANGERMS_IN1, 16, &mut d2b, 16, 0.9);
        assert_close(&d2b, CHANGERMS_OUT_R090, 1e-4, "change_rms 0.9");
    }

    // verified against np.pad(..., 'reflect') in the converter venv, incl. multi-bounce:
    //   np.pad([1,2,3],(5,5)) → [2,1,2,3,2,1,2,3,2,1,2,3,2]; np.pad([7],(3,2)) → all 7
    #[test]
    fn reflect_pad_matches_numpy() {
        assert_eq!(
            reflect_pad_np(&[1.0, 2.0, 3.0], 5, 5),
            vec![2.0, 1.0, 2.0, 3.0, 2.0, 1.0, 2.0, 3.0, 2.0, 1.0, 2.0, 3.0, 2.0]
        );
        assert_eq!(
            reflect_pad_np(&[1.0, 2.0, 3.0, 4.0], 2, 3),
            vec![3.0, 2.0, 1.0, 2.0, 3.0, 4.0, 3.0, 2.0, 1.0]
        );
        assert_eq!(reflect_pad_np(&[7.0], 3, 2), vec![7.0; 6]);
    }

    #[test]
    fn nearest_cluster_centers_picks_l2_nearest() {
        let centers = KnnIndex::new(
            Array2::from_shape_vec((3, 2), vec![0.0, 0.0, 10.0, 0.0, 0.0, 10.0]).unwrap(),
        );
        let feats = Array2::from_shape_vec((3, 2), vec![1.0, 1.0, 9.0, -1.0, -2.0, 8.0]).unwrap();
        let picked = nearest_cluster_centers(&feats, &centers);
        assert_eq!(picked.row(0).to_vec(), vec![0.0, 0.0]);
        assert_eq!(picked.row(1).to_vec(), vec![10.0, 0.0]);
        assert_eq!(picked.row(2).to_vec(), vec![0.0, 10.0]);
    }
}
