export const MUSCRIPTOR_INSTRUMENTS = [
  "acoustic_piano",
  "electric_piano",
  "chromatic_percussion",
  "organ",
  "acoustic_guitar",
  "clean_electric_guitar",
  "distorted_electric_guitar",
  "acoustic_bass",
  "electric_bass",
  "violin",
  "viola",
  "cello",
  "contrabass",
  "orchestral_harp",
  "timpani",
  "string_ensemble",
  "synth_strings",
  "voice",
  "orchestra_hit",
  "trumpet",
  "trombone",
  "tuba",
  "french_horn",
  "brass_section",
  "soprano_and_alto_sax",
  "tenor_sax",
  "baritone_sax",
  "oboe",
  "english_horn",
  "bassoon",
  "clarinet",
  "flutes",
  "synth_lead",
  "synth_pad",
  "drums",
] as const;

export const MUSCRIPTOR_ZH_LABELS: Record<string, string> = {
  acoustic_piano: "原声钢琴",
  electric_piano: "电钢琴",
  chromatic_percussion: "半音阶打击乐",
  organ: "风琴",
  acoustic_guitar: "原声吉他",
  clean_electric_guitar: "干净的电吉他",
  distorted_electric_guitar: "失真电吉他",
  acoustic_bass: "原声贝斯",
  electric_bass: "电贝斯",
  violin: "小提琴",
  viola: "中提琴",
  cello: "大提琴",
  contrabass: "低音提琴",
  orchestral_harp: "管弦乐竖琴",
  timpani: "定音鼓",
  string_ensemble: "弦乐合奏",
  synth_strings: "合成弦乐",
  voice: "人声",
  orchestra_hit: "管弦乐击奏",
  trumpet: "小号",
  trombone: "长号",
  tuba: "大号",
  french_horn: "圆号",
  brass_section: "铜管乐组",
  soprano_and_alto_sax: "高音及中音萨克斯",
  tenor_sax: "次中音萨克斯",
  baritone_sax: "上低音萨克斯",
  oboe: "双簧管",
  english_horn: "英国管",
  bassoon: "巴松管",
  clarinet: "单簧管",
  flutes: "长笛组",
  synth_lead: "合成主音",
  synth_pad: "合成铺底",
  drums: "鼓组",
};
