"""RVC training pipeline orchestration: the six stages the original webui ran as
separate buttons (preprocess -> f0 -> feature -> index -> filelist/config ->
train), driven from one run config. Stage order deviation vs upstream: the
retrieval matrix ("index") is built right after feature extraction instead of
after training — it only depends on the extracted features, so it exists even if
the user stops mid-training (the "index gen on stop" requirement, solved by
construction).

Run config (JSON, written by the Rust TrainingManager) — required keys:
  backend "rvc", workspace, dataset_dir, model_slug, sample_rate "32k|40k|48k",
  version "v1|v2", total_epoch, batch_size, stop_file,
  assets{ffmpeg, rmvpe_pt, contentvec_onnx, configs_dir, mute_dir}
optional: spk_id(0), seed(1234), per(3.7), fp16(true), save_every_epoch(5),
  save_every_weights(true), keep_only_latest(true), cache_gpu(false),
  pretrain_g(""), pretrain_d(""), aug_copies(0, S41 PSOLA copies per slice),
  gpu (handled by runner via CUDA_VISIBLE_DEVICES)

S41 augmentation stage order: slice -> augment (aug gt+16k twins; the slice
dirs are rebuilt every run so aug wavs are regenerated too — PSOLA is 130x+
realtime, and regenerated bytes are deterministic so the name-keyed f0/feature
caches stay valid) -> f0 -> feature -> aug_check (f0 gate on 2b-f0nsf Hz
floats; 2a is 256-bin coarse and unusable for cents) -> index (excludes _aug
features) -> filelist (4-dir intersection picks up surviving aug slices as
train data; RVC has no val split).
"""
import logging
import os

import numpy as np

from . import train_utils as utils
from ..augment import augment_slices, is_aug_name, list_aug_entries, read_wav, run_f0_gate
from ..cache import dataset_fingerprint, invalidate_extract_caches
from .extract_f0 import extract_f0
from .extract_feature import extract_features
from .filelist import build_filelist_and_config
from .index_npy import build_index
from .preprocess import preprocess_trainset
from .train import train

logger = logging.getLogger(__name__)

SR_MAP = {"32k": 32000, "40k": 40000, "48k": 48000}

# f0/feature caches are keyed by slice file name — see utai_train/cache.py
EXTRACT_CACHE_SUBDIRS = ("2a_f0", "2b-f0nsf", "3_feature256", "3_feature768")


def run(cfg, reporter, stop):
    import torch

    exp_dir = cfg["workspace"]
    os.makedirs(exp_dir, exist_ok=True)
    utils.get_logger(exp_dir)  # file log train.log (utf-8) in the run dir

    assets = cfg["assets"]
    sr_str = cfg["sample_rate"]
    if sr_str not in SR_MAP:
        raise RuntimeError("非法采样率: %s（可选 32k/40k/48k）" % sr_str)
    version = cfg["version"]
    seed = int(cfg.get("seed", 1234))
    fp16 = bool(cfg.get("fp16", True)) and torch.cuda.is_available()
    ffmpeg = assets["ffmpeg"]

    invalidate_extract_caches(
        exp_dir, dataset_fingerprint(cfg["dataset_dir"]), EXTRACT_CACHE_SUBDIRS
    )

    preprocess_trainset(
        cfg["dataset_dir"],
        SR_MAP[sr_str],
        exp_dir,
        float(cfg.get("per", 3.7)),
        ffmpeg,
        reporter,
        stop,
    )

    stop.check()
    _augment_rvc(exp_dir, int(cfg.get("aug_copies", 0)), seed, reporter, stop)

    use_cuda = torch.cuda.is_available()
    extract_f0(
        exp_dir,
        assets["rmvpe_pt"],
        "cuda" if use_cuda else "cpu",
        use_cuda,  # matches upstream's de-facto always-half-on-NVIDIA behavior
        ffmpeg,
        reporter,
        stop,
    )

    extract_features(exp_dir, version, assets["contentvec_onnx"], reporter, stop)

    stop.check()
    _rvc_aug_gate(exp_dir, reporter, stop)

    stop.check()
    index_path, index_rows = build_index(exp_dir, version, seed, reporter)

    stop.check()
    build_filelist_and_config(
        exp_dir,
        sr_str,
        version,
        int(cfg.get("spk_id", 0)),
        assets["configs_dir"],
        assets["mute_dir"],
        seed,
        fp16,
        reporter,
    )

    stop.check()
    reporter.stage("train_prep", message="加载模型与数据，训练即将开始")
    summary = train(cfg, exp_dir, reporter, stop)

    if summary["final_weight"] is None and not summary["stopped"]:
        raise RuntimeError(
            "没有执行任何训练步：目标 epoch (%s) 不大于已训练进度，请增大总 epoch 后再续训"
            % cfg["total_epoch"]
        )

    summary["index"] = index_path
    summary["index_rows"] = index_rows
    reporter.done("stopped" if summary.pop("stopped") else "completed", summary)


# ─── S41 PSOLA augmentation (design doc B3, rvc row) ─────────────────────────

# every product an aug slice owns, beyond its 0_gt_wavs wav (removal /
# stale-sweep clean list — red-team F8 "six-piece atomic group")
_RVC_AUG_PRODUCTS = (
    ("1_16k_wavs", ".wav"),
    ("2a_f0", ".wav.npy"),
    ("2b-f0nsf", ".wav.npy"),
    ("3_feature256", ".npy"),
    ("3_feature768", ".npy"),
)


def _rvc_meta_dir(exp_dir):
    return os.path.join(exp_dir, "aug_meta")


def _remove_rvc_aug_products(exp_dir, stem):
    for rel, suffix in (("0_gt_wavs", ".wav"),) + _RVC_AUG_PRODUCTS:
        p = os.path.join(exp_dir, rel, stem + suffix)
        try:
            os.remove(p)
        except OSError:
            pass
    try:
        os.remove(os.path.join(_rvc_meta_dir(exp_dir), stem + ".json"))
    except OSError:
        pass


def _augment_rvc(exp_dir, copies, seed, reporter, stop):
    import librosa
    from scipy.io import wavfile

    gt_dir = os.path.join(exp_dir, "0_gt_wavs")
    wav16k_dir = os.path.join(exp_dir, "1_16k_wavs")

    def write_gt(tmp_path, samples, sr):
        wavfile.write(tmp_path, sr, samples.astype(np.float32))

    def write_16k_twin(aug_stem, samples, sr):
        y16 = librosa.resample(samples, orig_sr=sr, target_sr=16000)
        tmp = os.path.join(wav16k_dir, aug_stem + ".wav.tmp")
        wavfile.write(tmp, 16000, y16.astype(np.float32))
        os.replace(tmp, os.path.join(wav16k_dir, aug_stem + ".wav"))

    augment_slices(
        gt_dir,
        copies,
        seed,
        _rvc_meta_dir(exp_dir),
        read_wav,
        write_gt,
        lambda stem: _remove_rvc_aug_products(exp_dir, stem),
        reporter,
        stop,
        companion_write_fn=write_16k_twin,
    )

    # stale-feature sweep (red-team R3): the slice dirs are wiped every run but
    # the f0/feature caches are not — aug entries whose wav no longer exists
    # (copies lowered, plan changed) must not linger where build_index /
    # skip-if-exists could see them
    current = {
        os.path.splitext(n)[0]
        for n in os.listdir(gt_dir)
        if n.endswith(".wav") and is_aug_name(n)
    }
    for rel, _suffix in _RVC_AUG_PRODUCTS:
        d = os.path.join(exp_dir, rel)
        if not os.path.isdir(d):
            continue
        for name in os.listdir(d):
            if is_aug_name(name) and name.split(".")[0] not in current:
                try:
                    os.remove(os.path.join(d, name))
                except OSError:
                    pass


def _rvc_aug_gate(exp_dir, reporter, stop):
    """f0 quality gate on the 2b-f0nsf products (Hz floats, unvoiced = 0,
    NOT interpolated — voiced mask is f0 > 0; 2a_f0 is the 256-bin coarse
    quantization and must never be used for cents comparisons)."""
    gt_dir = os.path.join(exp_dir, "0_gt_wavs")
    f0nsf_dir = os.path.join(exp_dir, "2b-f0nsf")

    def load_f0(stem):
        try:
            f0 = np.load(os.path.join(f0nsf_dir, stem + ".wav.npy"))
            f0 = np.asarray(f0, dtype=np.float64).reshape(-1)
            return f0, f0 > 0
        except Exception:
            logger.warning("gate: unreadable f0 product for %s", stem)
            return None

    run_f0_gate(
        list_aug_entries(gt_dir, _rvc_meta_dir(exp_dir)),
        load_f0,
        lambda stem: _remove_rvc_aug_products(exp_dir, stem),
        reporter,
        stop,
        report_path=os.path.join(exp_dir, "aug_gate_report.json"),
    )
