# -*- coding: utf-8 -*-
"""Write/check `src-tauri/dictionaries.sha256` — the committed identity of the shipped dictionaries.

WHY IT EXISTS (queue §H7, first baseline). Until now NOTHING in this repo pinned the BYTES of
`data/dictionaries/*.tsv`:

  * they are gitignored generated assets, so git does not carry them;
  * `release.ps1` checked only `Test-Path` — a stale or swapped TSV shipped silently;
  * the ~15 dictionary gates in `g2p.rs` pin PROPERTIES (a knife survived, a cluster count), not
    identity, and each of them SKIPS silently when the file is absent.

So the release path could produce an installer carrying a dictionary generation nobody chose, with
every gate green. That is the S98 shape exactly: same line count, same word set, same file size,
3051 German pronunciations different.

WHAT IT IS NOT. This does not replace `verify_dictionaries.py` (Much-Better-S2H `_onnx_derisk/`),
which regenerates from the upstream sources and compares byte-for-byte — that proves the files are
what the generator produces. This manifest proves the files are what we DECIDED to ship, from inside
`cargo test`, which is a hard gate in `release.ps1` §5 before the build.

FAIL-CLOSED ON PURPOSE. Regenerating a dictionary makes the Rust gate go red. That is the same rule
S105 chose for the onset tables: a dictionary change is a decision someone has to announce, not a
thing that slips through. The fix is one command — rerun `verify_dictionaries.py`, then
`py -3.10 scripts/dict_manifest.py --write`, and say so in the commit.

THE FILE LIST IS DERIVED, NEVER TYPED. It comes from `src-tauri/tauri.conf.json` `bundle.resources`
— the same single authority `bundled_dictionary_targets()` (Rust) reads. The list already exists in
four hand-kept copies elsewhere (release.ps1, verify-install.ps1, a settings.rs test, the
distribution test); this is deliberately not a fifth.

Run:
  py -3.10 scripts/dict_manifest.py            # check (exit 1 on any mismatch/absence)
  py -3.10 scripts/dict_manifest.py --write    # rewrite the manifest from what is on disk
"""
import argparse
import hashlib
import json
import os
import sys

sys.stdout.reconfigure(encoding="utf-8")

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, ".."))
CONF = os.path.join(REPO, "src-tauri", "tauri.conf.json")
DICT_DIR = os.path.join(REPO, "data", "dictionaries")
MANIFEST = os.path.join(REPO, "src-tauri", "dictionaries.sha256")
PREFIX = "data/dictionaries/"


def shipped_names():
    """Basenames of the dictionaries tauri.conf.json actually bundles. Mirrors the Rust
    `bundled_dictionary_targets()` filter exactly: value starts with data/dictionaries/ and is not
    a directory entry."""
    with open(CONF, encoding="utf-8") as fh:
        conf = json.load(fh)
    res = conf.get("bundle", {}).get("resources", {})
    if not isinstance(res, dict):
        raise SystemExit("bundle.resources is not an object — the Rust derivation is broken too")
    out = []
    for target in res.values():
        if isinstance(target, str) and target.startswith(PREFIX) and not target.endswith("/"):
            out.append(target[len(PREFIX):])
    if not out:
        raise SystemExit("bundle.resources yielded 0 dictionaries — refusing to write an empty manifest")
    return sorted(out)


def sha256_of(path):
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def read_manifest():
    rows = {}
    if not os.path.exists(MANIFEST):
        return rows
    with open(MANIFEST, encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            digest, _, name = line.partition("  ")
            if digest and name:
                rows[name.strip()] = digest.strip()
    return rows


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true", help="rewrite the manifest from disk")
    args = ap.parse_args()

    names = shipped_names()
    missing = [n for n in names if not os.path.isfile(os.path.join(DICT_DIR, n))]
    if missing:
        print("ABSENT from %s: %s" % (DICT_DIR, ", ".join(missing)))
        if args.write:
            raise SystemExit("refusing to write a manifest that would not cover every bundled file")

    live = {n: sha256_of(os.path.join(DICT_DIR, n)) for n in names if n not in missing}

    if args.write:
        lines = [
            "# sha256 of the dictionaries this build ships. Generated by scripts/dict_manifest.py;",
            "# NEVER hand-edit. Regenerated a dictionary? Rerun verify_dictionaries.py first, then",
            "# `py -3.10 scripts/dict_manifest.py --write`, and name the change in the commit.",
            "# File list derived from src-tauri/tauri.conf.json bundle.resources.",
        ]
        for n in names:
            lines.append("%s  %s" % (live[n], n))
        with open(MANIFEST, "w", encoding="utf-8", newline="\n") as fh:
            fh.write("\n".join(lines) + "\n")
        print("wrote %s (%d entries)" % (MANIFEST, len(names)))
        for n in names:
            print("  %s  %s" % (live[n][:16], n))
        return 0

    want = read_manifest()
    if not want:
        print("NO MANIFEST at %s — run with --write" % MANIFEST)
        return 1
    bad = []
    for n in names:
        if n not in want:
            bad.append("%s: not in the manifest (bundle.resources gained a file?)" % n)
        elif n in missing:
            bad.append("%s: absent on disk" % n)
        elif want[n] != live[n]:
            bad.append("%s: %s on disk, manifest says %s" % (n, live[n][:16], want[n][:16]))
    for extra in sorted(set(want) - set(names)):
        bad.append("%s: in the manifest but no longer bundled" % extra)
    if bad:
        print("MISMATCH:")
        for b in bad:
            print("  " + b)
        return 1
    print("CLEAN — %d dictionaries match %s" % (len(names), os.path.relpath(MANIFEST, REPO)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
